language: elixir
elixir:
  - '1.7'

script:
  - mix test --cover
  - mix format --check-formatted

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
