language: elixir
elixir:
  - '1.6'

script:
 - mix format --check-formatted
 - mix test

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

matrix:
  include:
  - elixir: '1.7'
